server:
  port: 4002
spring:
  application:
    name:  ms-bootcoin-wallet-balance-service
 # config:
  #  import: optional:configserver:http://ms-bank-config-server:8888
  data: 
    mongodb:
     host: localhost
     port: 27017
     database: Bootcoin 
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
        group-id: myGroup
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

kafka:
  topic:
    bootcoin:
      wallet-balance:
        create:
          name: bootcoin-wallet-balance-create
